name: TownyFly
main: thevoxstudios.vtownyfly.TownyFly
description: Allowing Members to fly in their joined town.
author: TheMasteredPanda
version: '1.0'
depend: [Towny]
commands:
  tfly:
    description: Usage for the command
    permission: vox.towny.fly
